activation:device_id,phone_os,phone_model,phone_user_info,phone_number,type,addtime,ip
thirdinfo: 有疑问
user_action:user_id,isOldUser,addtime,account,add_ip,action,add_product,version,add_channel
user_behavior: 有疑问
xinshen_approve_log:user_id,borrow_nid,addtime,updatetime,operater_id,operater_name,code,memo,before_key,before_value,after_key,after_value
xinshen_approve_full_log:有疑问
alipay_request:有疑问
credit100_auth_log:
mcookie:userId,_class,addtime,userHead,userCookie,ip,type,addProudct,addChannel



#activation
create table mongo.pq_activation(device_id string,add_channel string,add_product string,addtime string,device_id_type string,idfa string,imei string,ip string,mac string,phone_model string,phone_number string,phone_os string,type string)
COMMENT 'pq_activation parquet file'
PARTITIONED BY(yr STRING,mn STRING,dt STRING)
STORED AS PARQUET;



create table tmp.activation_tmp(device_id string,add_channel string,add_product string,addtime string,device_id_type string,idfa string,imei string,ip string,mac string,phone_model string,phone_number string,phone_os string,type string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '`';



#user_action
create table mongo.pq_user_action(user_id string,isOldUser string,addtime string,account string,add_ip string,action string,add_product string,version string,add_channel string,content string,utm_tag string)
COMMENT 'user_action parquet file'
PARTITIONED BY(yr STRING,mn STRING,dt STRING)
CLUSTERED BY(user_id)  INTO 32 BUCKETS
STORED AS PARQUET;

#user_action
create table mongo.pq_user_action_hour(user_id string,isOldUser string,addtime string,account string,add_ip string,action string,add_product string,version string,add_channel string,content string,utm_tag string)
COMMENT 'user_action parquet file'
PARTITIONED BY(yr STRING,mn STRING,dt STRING,hr STRING)
CLUSTERED BY(user_id)  INTO 32 BUCKETS
STORED AS PARQUET;



create table tmp.user_action_tmp(user_id string,isOldUser string,addtime string,account string,add_ip string,action string,add_product string,version string,add_channel string,content string,utm_tag string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '`';



#xinshen_approve_log
create table mongo.pq_xinshen_approve_log(user_id string,borrow_nid string,addtime string,updatetime string,operater_id string,operater_name string,code string,memo string,before_key string,before_value string,after_key string,after_value string)
COMMENT 'xinshen_approve_log parquet file'
PARTITIONED BY(yr STRING,mn STRING,dt STRING)
CLUSTERED BY(user_id)  INTO 32 BUCKETS
STORED AS PARQUET;



create table tmp.xinshen_approve_log_tmp(user_id string,borrow_nid string,addtime string,updatetime string,operater_id string,operater_name string,code string,memo string,before_key string,before_value string,after_key string,after_value string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '`';


#mcookie
create table mongo.pq_mcookie(userId string,addtime string,userCookie string,ip string,type string,addProudct string,addChannel string,userHead_REDIRECT_UNIQUE_ID string,userHead_REDIRECT_STATUS string,userHead_UNIQUE_ID string,userHead_HTTP_HOST string,userHead_HTTP_X_REAL_IP string,userHead_HTTP_X_FORWARDED_FOR string,userHead_HTTP_CONNECTION string,userHead_HTTP_USER_AGENT string,userHead_HTTP_WEB_SERVER_TYPE string,userHead_HTTP_WL_PROXY_CLIENT_IP string,userHead_HTTP_X_FORWARDED_PROTO string,userHead_HTTP_X_FORWARDED_CLUSTER string,userHead_HTTP_VIA string,userHead_HTTP_EAGLEEYE_TRACEID string,userHead_HTTP_ALI_SWIFT_LOG_HOST string,userHead_HTTP_X_CLIENT_SCHEME string,userHead_HTTP_ALI_CDN_REAL_IP string,userHead_HTTP_ACCEPT string,userHead_HTTP_UPGRADE_INSECURE_REQUESTS string,userHead_HTTP_COOKIE string,userHead_HTTP_ACCEPT_LANGUAGE string,userHead_HTTP_ACCEPT_ENCODING string,userHead_PATH string,userHead_SERVER_SIGNATURE string,userHead_SERVER_SOFTWARE string,userHead_SERVER_NAME string,userHead_SERVER_ADDR string,userHead_SERVER_PORT string,userHead_REMOTE_ADDR string,userHead_DOCUMENT_ROOT string,userHead_SERVER_ADMIN string,userHead_SCRIPT_FILENAME string,userHead_REMOTE_PORT string,userHead_REDIRECT_QUERY_STRING string,userHead_REDIRECT_URL string,userHead_GATEWAY_INTERFACE string,userHead_SERVER_PROTOCOL string,userHead_REQUEST_METHOD string,userHead_QUERY_STRING string,userHead_REQUEST_URI string,userHead_SCRIPT_NAME string,userHead_PATH_INFO string,userHead_PATH_TRANSLATED string,userHead_PHP_SELF string,userHead_REQUEST_TIME string)
COMMENT 'mcookie parquet file'
PARTITIONED BY(yr STRING,mn STRING,dt STRING)
CLUSTERED BY(userid)  INTO 32 BUCKETS
STORED AS PARQUET;



create table tmp.mcookie_tmp(userId string,addtime string,userCookie string,ip string,type string,addProudct string,addChannel string,userHead_REDIRECT_UNIQUE_ID string,userHead_REDIRECT_STATUS string,userHead_UNIQUE_ID string,userHead_HTTP_HOST string,userHead_HTTP_X_REAL_IP string,userHead_HTTP_X_FORWARDED_FOR string,userHead_HTTP_CONNECTION string,userHead_HTTP_USER_AGENT string,userHead_HTTP_WEB_SERVER_TYPE string,userHead_HTTP_WL_PROXY_CLIENT_IP string,userHead_HTTP_X_FORWARDED_PROTO string,userHead_HTTP_X_FORWARDED_CLUSTER string,userHead_HTTP_VIA string,userHead_HTTP_EAGLEEYE_TRACEID string,userHead_HTTP_ALI_SWIFT_LOG_HOST string,userHead_HTTP_X_CLIENT_SCHEME string,userHead_HTTP_ALI_CDN_REAL_IP string,userHead_HTTP_ACCEPT string,userHead_HTTP_UPGRADE_INSECURE_REQUESTS string,userHead_HTTP_COOKIE string,userHead_HTTP_ACCEPT_LANGUAGE string,userHead_HTTP_ACCEPT_ENCODING string,userHead_PATH string,userHead_SERVER_SIGNATURE string,userHead_SERVER_SOFTWARE string,userHead_SERVER_NAME string,userHead_SERVER_ADDR string,userHead_SERVER_PORT string,userHead_REMOTE_ADDR string,userHead_DOCUMENT_ROOT string,userHead_SERVER_ADMIN string,userHead_SCRIPT_FILENAME string,userHead_REMOTE_PORT string,userHead_REDIRECT_QUERY_STRING string,userHead_REDIRECT_URL string,userHead_GATEWAY_INTERFACE string,userHead_SERVER_PROTOCOL string,userHead_REQUEST_METHOD string,userHead_QUERY_STRING string,userHead_REQUEST_URI string,userHead_SCRIPT_NAME string,userHead_PATH_INFO string,userHead_PATH_TRANSLATED string,userHead_PHP_SELF string,userHead_REQUEST_TIME string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '`';


#credit100_auth_log
create table mongo.pq_credit100_auth_log(user_id string,borrow_nid string,addtime string,validate string,credit100Eexecute_cons_m6_fzps_visits string,credit100Eexecute_sl_id_a1_degree string,credit100Eexecute_cons_m12_tx_level string,credit100Eexecute_cons_m12_tx_maxpay string,credit100Eexecute_ac_m1m3_credit_in string,credit100Eexecute_cons_m12_ydhw_level string,credit100Eexecute_cons_m3_fzps_visits string,credit100Eexecute_stab_cell_num string,credit100Eexecute_cons_m12_tx_visits string,credit100Eexecute_cons_m12_n_avgpay string,credit100Eexecute_cons_m3_whyl_visits string,credit100Eexecute_cons_m3_n_avgpay string,credit100Eexecute_max_cons_m6_numcate string,credit100Eexecute_cons_m12_cwsh_visits string,credit100Eexecute_cons_m3_tx_pay string,credit100Eexecute_max_cons_m3_pay string,credit100Eexecute_cons_m6_ghhz_visits string,credit100Eexecute_ac_m1m3_debit_in string,credit100Eexecute_max_cons_m3_numcate string,credit100Eexecute_sl_id_b1_degree string,credit100Eexecute_ac_m4m6_debit_out string,credit100Eexecute_cons_m3_wlyxxnwp_visits string,credit100Eexecute_sl_id_b2_degree string,credit100Eexecute_is_cons_m3_jjqc_num string,credit100Eexecute_cons_m12_fc_visits string,credit100Eexecute_sl_cell_b5_degree string,credit100Eexecute_al_m6_id_notbank_orgnum string,credit100Eexecute_swift_number string,credit100Eexecute_al_m6_cell_notbank_orgnum string,credit100Eexecute_al_m12_id_notbank_orgnum string,credit100Eexecute_al_m6_id_notbank_allnum string,credit100Eexecute_al_m3_cell_bank_allnum string,credit100Eexecute_al_m3_cell_notbank_selfnum string,credit100Eexecute_flag_rulespeciallist string,credit100Eexecute_flag_specialList_c string,credit100Eexecute_al_m12_cell_bank_selfnum string,credit100Eexecute_al_m12_id_notbank_allnum string,credit100Eexecute_al_m12_id_bank_selfnum string,credit100Eexecute_al_m3_cell_bank_orgnum string,credit100Eexecute_al_m6_id_bank_allnum string,credit100Eexecute_al_m6_id_bank_selfnum string,credit100Eexecute_Rule_final_decision string,credit100Eexecute_al_m6_cell_notbank_allnum string,credit100Eexecute_al_m3_id_bank_selfnum string,credit100Eexecute_flag_ruleapplyloan string,credit100Eexecute_al_m6_cell_bank_selfnum string,credit100Eexecute_Rule_weight_QJF030 string,credit100Eexecute_al_m3_id_notbank_selfnum string,credit100Eexecute_al_m6_cell_notbank_selfnum string,credit100Eexecute_al_m12_id_bank_orgnum string,credit100Eexecute_al_m12_id_bank_allnum string,credit100Eexecute_al_m12_cell_notbank_orgnum string,credit100Eexecute_al_m12_id_notbank_selfnum string,credit100Eexecute_al_m6_cell_bank_allnum string,credit100Eexecute_code string,credit100Eexecute_al_m3_cell_bank_selfnum string,credit100Eexecute_Rule_name_QJF030 string,credit100Eexecute_Rule_final_weight string,credit100Eexecute_flag_applyLoan string,credit100Eexecute_al_m3_cell_notbank_allnum string,credit100Eexecute_al_m6_cell_bank_orgnum string,credit100Eexecute_al_m3_id_bank_allnum string,credit100Eexecute_al_m6_id_notbank_selfnum string,credit100Eexecute_al_m3_cell_notbank_orgnum string,credit100Eexecute_al_m12_cell_notbank_allnum string,credit100Eexecute_al_m12_cell_bank_allnum string,credit100Eexecute_al_m12_cell_notbank_selfnum string,credit100Eexecute_al_m12_cell_bank_orgnum string,credit100Eexecute_al_m3_id_bank_orgnum string,credit100Eexecute_al_m3_id_notbank_allnum string,credit100Eexecute_al_m6_id_bank_orgnum string,credit100Eexecute_al_m3_id_notbank_orgnum string,credit100Eexecute_Flag string,credit100Eexecute_flag_media_c string,credit100Eexecute_scorecust string,credit100Eexecute_flag_score string,credit100Eexecute_flag_consumption_c string,credit100Eexecute_flag_stability_c string,req_borrowNid string,req_cell string,req_bank_running_att_num string,req_apiType string,req_id string,req_qlModuleType string,req_refund_periods string,req_income string,req_age string,req_app_visit_num string,req_name string,req_tokenid string,req_edu_att_num string,req_qlMeal string,req_userId string,req_gid string)
COMMENT 'credit100_auth_log parquet file'
PARTITIONED BY(yr STRING,mn STRING,dt STRING)
CLUSTERED BY(user_id)  INTO 32 BUCKETS
STORED AS PARQUET;



create table tmp.credit100_auth_log_tmp(user_id string,borrow_nid string,addtime string,validate string,credit100Eexecute_cons_m6_fzps_visits string,credit100Eexecute_sl_id_a1_degree string,credit100Eexecute_cons_m12_tx_level string,credit100Eexecute_cons_m12_tx_maxpay string,credit100Eexecute_ac_m1m3_credit_in string,credit100Eexecute_cons_m12_ydhw_level string,credit100Eexecute_cons_m3_fzps_visits string,credit100Eexecute_stab_cell_num string,credit100Eexecute_cons_m12_tx_visits string,credit100Eexecute_cons_m12_n_avgpay string,credit100Eexecute_cons_m3_whyl_visits string,credit100Eexecute_cons_m3_n_avgpay string,credit100Eexecute_max_cons_m6_numcate string,credit100Eexecute_cons_m12_cwsh_visits string,credit100Eexecute_cons_m3_tx_pay string,credit100Eexecute_max_cons_m3_pay string,credit100Eexecute_cons_m6_ghhz_visits string,credit100Eexecute_ac_m1m3_debit_in string,credit100Eexecute_max_cons_m3_numcate string,credit100Eexecute_sl_id_b1_degree string,credit100Eexecute_ac_m4m6_debit_out string,credit100Eexecute_cons_m3_wlyxxnwp_visits string,credit100Eexecute_sl_id_b2_degree string,credit100Eexecute_is_cons_m3_jjqc_num string,credit100Eexecute_cons_m12_fc_visits string,credit100Eexecute_sl_cell_b5_degree string,credit100Eexecute_al_m6_id_notbank_orgnum string,credit100Eexecute_swift_number string,credit100Eexecute_al_m6_cell_notbank_orgnum string,credit100Eexecute_al_m12_id_notbank_orgnum string,credit100Eexecute_al_m6_id_notbank_allnum string,credit100Eexecute_al_m3_cell_bank_allnum string,credit100Eexecute_al_m3_cell_notbank_selfnum string,credit100Eexecute_flag_rulespeciallist string,credit100Eexecute_flag_specialList_c string,credit100Eexecute_al_m12_cell_bank_selfnum string,credit100Eexecute_al_m12_id_notbank_allnum string,credit100Eexecute_al_m12_id_bank_selfnum string,credit100Eexecute_al_m3_cell_bank_orgnum string,credit100Eexecute_al_m6_id_bank_allnum string,credit100Eexecute_al_m6_id_bank_selfnum string,credit100Eexecute_Rule_final_decision string,credit100Eexecute_al_m6_cell_notbank_allnum string,credit100Eexecute_al_m3_id_bank_selfnum string,credit100Eexecute_flag_ruleapplyloan string,credit100Eexecute_al_m6_cell_bank_selfnum string,credit100Eexecute_Rule_weight_QJF030 string,credit100Eexecute_al_m3_id_notbank_selfnum string,credit100Eexecute_al_m6_cell_notbank_selfnum string,credit100Eexecute_al_m12_id_bank_orgnum string,credit100Eexecute_al_m12_id_bank_allnum string,credit100Eexecute_al_m12_cell_notbank_orgnum string,credit100Eexecute_al_m12_id_notbank_selfnum string,credit100Eexecute_al_m6_cell_bank_allnum string,credit100Eexecute_code string,credit100Eexecute_al_m3_cell_bank_selfnum string,credit100Eexecute_Rule_name_QJF030 string,credit100Eexecute_Rule_final_weight string,credit100Eexecute_flag_applyLoan string,credit100Eexecute_al_m3_cell_notbank_allnum string,credit100Eexecute_al_m6_cell_bank_orgnum string,credit100Eexecute_al_m3_id_bank_allnum string,credit100Eexecute_al_m6_id_notbank_selfnum string,credit100Eexecute_al_m3_cell_notbank_orgnum string,credit100Eexecute_al_m12_cell_notbank_allnum string,credit100Eexecute_al_m12_cell_bank_allnum string,credit100Eexecute_al_m12_cell_notbank_selfnum string,credit100Eexecute_al_m12_cell_bank_orgnum string,credit100Eexecute_al_m3_id_bank_orgnum string,credit100Eexecute_al_m3_id_notbank_allnum string,credit100Eexecute_al_m6_id_bank_orgnum string,credit100Eexecute_al_m3_id_notbank_orgnum string,credit100Eexecute_Flag string,credit100Eexecute_flag_media_c string,credit100Eexecute_scorecust string,credit100Eexecute_flag_score string,credit100Eexecute_flag_consumption_c string,credit100Eexecute_flag_stability_c string,req_borrowNid string,req_cell string,req_bank_running_att_num string,req_apiType string,req_id string,req_qlModuleType string,req_refund_periods string,req_income string,req_age string,req_app_visit_num string,req_name string,req_tokenid string,req_edu_att_num string,req_qlMeal string,req_userId string,req_gid string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '`';



#xinshen_approve_full_log
create table mongo.pq_xinshen_approve_full_log(user_id string,borrow_nid string,approve_info_check string,approve_info_hash string,risk_code_log string,approve_note_tv1 string,approve_note_tv2 string,approve_note_tv3 string,approve_note_tv_describe string,approve_note_version string,approve_special_ai string,approve_special_ae string,approve_special_oc string,approve_special_oh string,approve_special_spc string,approve_special_spc2 string,approve_special_spc3 string,approve_special_sy string,approve_special_registered_capital string,approve_special_registered_time string,approve_special_version string,approve_remark_remarks string,approve_remark_personal_remarks string,approve_remark_version string,approve_conclusion_conclusion string,approve_conclusion_money string,approve_conclusion_reason_code1 string,approve_conclusion_reason_code2 string,approve_conclusion_reason_code3 string,approve_conclusion_version string,approve_conclusion_amount string,approve_conclusion_equipment_matching string,approve_conclusion_stage string,approve_conclusion_latest_money string)
COMMENT 'xinshen_approve_full_log parquet file'
PARTITIONED BY(yr STRING,mn STRING,dt STRING)
CLUSTERED BY(user_id)  INTO 32 BUCKETS
STORED AS PARQUET;



create table tmp.xinshen_approve_full_log_tmp(user_id string,borrow_nid string,approve_info_check string,approve_info_hash string,risk_code_log string,approve_note_tv1 string,approve_note_tv2 string,approve_note_tv3 string,approve_note_tv_describe string,approve_note_version string,approve_special_ai string,approve_special_ae string,approve_special_oc string,approve_special_oh string,approve_special_spc string,approve_special_spc2 string,approve_special_spc3 string,approve_special_sy string,approve_special_registered_capital string,approve_special_registered_time string,approve_special_version string,approve_remark_remarks string,approve_remark_personal_remarks string,approve_remark_version string,approve_conclusion_conclusion string,approve_conclusion_money string,approve_conclusion_reason_code1 string,approve_conclusion_reason_code2 string,approve_conclusion_reason_code3 string,approve_conclusion_version string,approve_conclusion_amount string,approve_conclusion_equipment_matching string,approve_conclusion_stage string,approve_conclusion_latest_money string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '`';
